name: VoxelSniperRegions
main: com.empcraft.vsr.VoxelSniperRegions
version: 0.4.2
depend: [VoxelSniper]
softdepend: [PlotMe, Worldedit,WorldGuard,GriefPrevention,PreciousStones,Towny,Factions,Residence,ProtocolLib,CoreProtect]
commands:
   vsr:
      description: All VoxelSniper Regions Commands