name: VoxelSniperRegions
main: com.empcraft.vsr.VoxelSniperRegions
version: 0.3.3
depend: [VoxelSniper]
softdepend: [Worldedit,WorldGuard,GriefPrevention,PreciousStones,Towny,Factions,Residence,ProtocolLib]
commands:
   vsr:
      description: All VoxelSniper Regions Commands